inherit_from: .rubocop_todo.yml

AllCops:
  AutoCorrect: false
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/*'

Bundler/OrderedGems:
  AutoCorrect: true

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

#Style/Alias:
#  EnforcedStyle: prefer_alias_method

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Enabled: false

# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 30

# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 35

Layout/LineLength:
  Max: 160
